### ISSUE TITLE
ffprobe error

### ISSUE THREAD

**Issue by howardlau1999** [bytedance/music_source_separation#11]
Hi, I created a new Anaconda3 environment and installed the requirements and downloaded musdb18 using the command line in the README. But I could not pack them into hdf5:

```bash
$ PYTHONPATH=. ./scripts/1_pack_audios_to_hdf5s/musdb18/sr=44100,chn=2.sh
MUSDB18_DATASET_DIR=./datasets/musdb18
WORKSPACE=./workspaces/bytesep
Traceback (most recent call last):
  File "bytesep/dataset_creation/pack_audios_to_hdf5s/musdb18.py", line 195, in <module>
    pack_audios_to_hdf5s(args)
  File "bytesep/dataset_creation/pack_audios_to_hdf5s/musdb18.py", line 37, in pack_audios_to_hdf5s
    mus = musdb.DB(root=dataset_dir, subsets=[subset], split=split)
  File "/data1/howard/anaconda3/lib/python3.8/site-packages/musdb/__init__.py", line 115, in __init__
    self.tracks = self.load_mus_tracks(subsets=subsets, split=split)
  File "/data1/howard/anaconda3/lib/python3.8/site-packages/musdb/__init__.py", line 256, in load_mus_tracks
    track = MultiTrack(
  File "/data1/howard/anaconda3/lib/python3.8/site-packages/musdb/audio_classes.py", line 133, in __init__
    super(MultiTrack, self).__init__(path=path, *args, **kwargs)
  File "/data1/howard/anaconda3/lib/python3.8/site-packages/musdb/audio_classes.py", line 52, in __init__
    self.info = stempeg.Info(self.path)
  File "/data1/howard/anaconda3/lib/python3.8/site-packages/stempeg/read.py", line 328, in __init__
    self.info = ffmpeg.probe(filename)
  File "/data1/howard/anaconda3/lib/python3.8/site-packages/ffmpeg/_probe.py", line 23, in probe
    raise Error('ffprobe', out, err)
ffmpeg._run.Error: ffprobe error (see stderr output for detail)
```

I have installed ffmpeg using `conda install -c conda-forge ffmpeg`

**Comment by qiuqiangkong** [comment]
We use musdb package: https://github.com/sigsep/sigsep-mus-db to read audio recordings. Maybe try "sudo apt-get install ffmpeg"?

**Comment by howardlau1999** [comment]
> We use musdb package: https://github.com/sigsep/sigsep-mus-db to read audio recordings. Maybe try "sudo apt-get install ffmpeg"?

This works. Thank you!
