### ISSUE TITLE
How can i install inplace-abn

### ISSUE THREAD

**Issue by GMPHL** [bytedance/music_source_separation#21]
Some errors occurred during installation

The error is:
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
    Error in atexit._run_exitfuncs:
    Traceback (most recent call last):
      File "E:\Sotfware\anaconda\envs\torch\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\Sotfware\anaconda\envs\torch\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\HASEE\\AppData\\Local\\Temp\\pip-install-983wdizd\\inplace-abn_a
aaed263bb064ef2b4c50af117b614df\\setup.py'"'"'; __file__='"'"'C:\\Users\\HASEE\\AppData\\Local\\Temp\\pip-install-983wdizd\\inplace-abn_aaaed263bb064ef2b4c50af117b614df\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file_
_) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\
HASEE\AppData\Local\Temp\pip-record-c2alay5x\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\Sotfware\anaconda\envs\torch\Include\inplace-abn' Check the logs for full command output.

So how can i install inplace-abn?
thanks

**Comment by GMPHL** [comment]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "E:\Sotfware\anaconda\lib\site-packages\colorama\initialise.py", line 20, in reset_all
      AnsiToWin32(orig_stdout).reset_all()
    File "E:\Sotfware\anaconda\lib\site-packages\colorama\ansitowin32.py", line 71, in __init__
      strip = conversion_supported or (not is_stream_closed(wrapped) and not is_a_tty(wrapped))
    File "E:\Sotfware\anaconda\lib\site-packages\colorama\ansitowin32.py", line 17, in is_stream_closed
      return not hasattr(stream, 'closed') or stream.closed
  ValueError: underlying buffer has been detached

  ----------------------------------------
  Failed building wheel for inplace-abn

it seems like a same error

**Comment by qiuqiangkong** [comment]
Not sure if it because inplace-abn does not support windows. One way is
ignore inplace-abn. The subband ResUNet does not require inplace-abn.

**Comment by GMPHL** [comment]
In linux, another error occurred:
python3.8/site-packages/inplace_abn/_backend.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at11leaky_relu_ERNS_6TensorERKN3c106ScalarE

In Linux environment also reports this error after pip install bytesep finished.Maybe i should replace the abn with nn.BatchNorm2d?and train the dataset for a new model?
