### ISSUE TITLE
Checkpoint is incomplete, please download again! 

### ISSUE THREAD

**Issue by WUxingChong** [bytedance/music_source_separation#41]
您好，我成功分离了vocals之后，再去分离accompaniment的时候就提示报错提示了Checkpoint文件不完整，我看了下script和模型文件都在，重新下载了也是报同样的错

Traceback (most recent call last):
  File "E:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\lib\site-packages\bytesep\__main__.py", line 242, in <module>
    separate(args)
  File "E:\Anaconda3\lib\site-packages\bytesep\__main__.py", line 162, in separate
    config_yaml, checkpoint_path = get_paths(source_type, model_type)
  File "E:\Anaconda3\lib\site-packages\bytesep\__main__.py", line 127, in get_paths
    assert os.path.getsize(checkpoint_path) == 414046363, error_message
AssertionError: Checkpoint is incomplete, please download again!

**Comment by aadsache** [comment]
在bytesep_main_.py文件内把这个断言注释了就行了，这个size判断可以跳过~ 希望对你有用

**Comment by SauravRai** [comment]
@WUxingChong I had the same issue. It seems if we manually download the checkpoints from the provided link [https://zenodo.org/records/5804160](url) that works.
