### ISSUE TITLE
No module named '_bz2'

### ISSUE THREAD

**Issue by jinleileiking** [bytedance/music_source_separation#69]
❯ python -m bytesep download_checkpoints

Traceback (most recent call last):
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/jinlei/oss/music_source_separation/bytesep/__init__.py", line 1, in <module>
    from bytesep.models.lightning_modules import get_model_class
  File "/home/jinlei/oss/music_source_separation/bytesep/models/__init__.py", line 1, in <module>
    from bytesep.models.lightning_modules import get_model_class
  File "/home/jinlei/oss/music_source_separation/bytesep/models/lightning_modules.py", line 3, in <module>
    import pytorch_lightning as pl
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/__init__.py", line 63, in <module>
    from pytorch_lightning.callbacks import Callback
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/callbacks/base.py", line 22, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.lightning import LightningModule
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 39, in <module>
    from pytorch_lightning.core.saving import ALLOWED_CONFIG_TYPES, ModelIO, PRIMITIVE_TYPES
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/core/saving.py", line 31, in <module>
    from pytorch_lightning.utilities.cloud_io import get_filesystem
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/pytorch_lightning/utilities/cloud_io.py", line 20, in <module>
    import fsspec
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/fsspec/__init__.py", line 12, in <module>
    from .compression import available_compressions
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/site-packages/fsspec/compression.py", line 2, in <module>
    from bz2 import BZ2File
  File "/home/jinlei/.pyenv/versions/3.7.17/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

**Comment by jinleileiking** [comment]
https://github.com/pyenv/pyenv/wiki#suggested-build-environment
